# Generated by Django 4.0.4 on 2022-04-29 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('blogid', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.TextField(max_length=200)),
                ('Body', models.TextField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
